---
- hosts: all
  tasks:
    - name: "Install git"
      apt: name=git state=latest

    - name: "Install java JDK 8"
      apt: name=openjdk-8-jdk state=latest

    - name: "Install maven"
      apt: name=maven state=latest

    - name: "Install udev config file"
      copy:
        src: files/51-android.rules
        dest: /etc/udev/rules.d/51-android.rules
        owner: root
        group: root
        mode: 0644
